# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
markdown: kramdown
remote_theme: daviddarnes/alembic

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
author: Vincent Poirier # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Vincent Poirier # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/20100poirier
    - https://www.linkedin.com/in/poirier20100
    - https://github.com/eradash
  # markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
  # commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Montreal # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: ""
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
title: Vincent Poirier
email: poirier.20.100@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Passionate developper working principally with Java on Android. I love
  Python and Docker too!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eradash.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  eradash
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
repo: "https://github.com/eradash/eradash.github.io"
avatarurl: "https://s.gravatar.com/avatar/1183dddd994597df57a68eeed46ab297" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/
  Categories: /categories/
#  Search: /search/

navigation_footer:
  Created with Alembic: https://github.com/daviddarnes/alembic

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/poirier20100
  facebook: https://www.facebook.com/20100poirier
  GitHub: https://github.com/eradash
